### ISSUE TITLE
Network API not recognized on iOS and Android

### ISSUE THREAD

**Issue by alexradulescu** [tubalmartin/riloadr#10]
Hi,

I am building a webapplication for both mobile and tablets and while testing I found that both on iOS and Android, if the screen is a retina display and I am on EDGE or 3G networks, riloadr still loads the highrez image.
Is there any possibility or changing to a different API?
You can find my test at http://alex034e.keaweb.dk/ .

Thank you

**Comment by tubalmartin** [comment]
Sorry for my late response, I've been really busy lately.

On Android 2.2+ it should work as per http://mobilehtml5.org/ compatibility tables. Make sure you set `ignoreLowBandwidth` to `false`.

As a side note, I do mention in the [docs](https://github.com/tubalmartin/riloadr#ignorelowbandwidth-boolean--optional) the support of the W3C Network API is still rather poor and there's not an alternative API, sorry :(
