### ISSUE TITLE
riloadr loading all images when mode: 'invisible' 

### ISSUE THREAD

**Issue by ghost** [tubalmartin/riloadr#12]
I'm setting up a group as follows:

```
    var group1 = new Riloadr({
        name: 'sub1',
        defer: {
            mode: 'invisible',
            threshold: 125
        }
    });
```

No matter what I do, the images seem to all load when the page loads. 

   img class="sub1" data-src="....">
   img class="sub1" data-src="....">
   img class="sub1" data-src="....">
...

Watching the HTTP requests run through fiddler.

I'm using Riloadr.js 1.4.3 in Chrome.

**Comment by tubalmartin** [comment]
That's only possible if those images are "visible to Riloadr" when the page loads. Try the demo on your local machine, edit demos/scripts/main.js, comment all Riloadr groups except groups 2, 7, 8 & 9 and see it for yourself.

**Comment by tubalmartin** [comment]
I can't access your demo, the page does not exist :(

Túbal Martín
www.margenn.com

2013/7/24 WarrickF notifications@github.com

**Comment by ghost** [comment]
Dou! 

It's up for your viewing pleasure again: 
http://www.dockspotter.com:3000/GreenwoodLake2.html 

I added the logic to the same event handler that the demo uses for Group2.

Part of my confusion was that I only had a few images and the page would not do anything. Now when you click the button you get a scroll bar ... and when you start scrolling it works ... but it seems to load all the images in one shot?

The really weird thing is that I'm hacking the example as close as possible and the demo works fine?
