### ISSUE TITLE
Adding window.innerWidth to 'widths' array

### ISSUE THREAD

**Issue by daleyjem** [tubalmartin/riloadr#19]
So far I've only seen an issue with IE8 out of IE8+, Chrome and FF. How would you feel about adding that to the array of 'widths'?

I noticed today that Chrome wasn't working properly when the viewport was 700px. It thought the viewport was 685px because of the scrollbar. So my CSS media queries were adjusting correctly, but riloadr was not. window.innerWidth fixed this.

**Comment by tubalmartin** [comment]
Thanks for the report! 

Could you try loading [this page](http://tubalmartin.me/riloadr/test.html) in IE8 to check if the output of getViewportWidthInCssPixels() equals the expected value?

**Comment by tubalmartin** [comment]
Fixed in 1.5.1! Thank you for reporting!
