### ISSUE TITLE
min height

### ISSUE THREAD

**Issue by condensed-io** [tubalmartin/riloadr#6]
```
        min-height: 100px /* To give responsive images some height until loaded. */
```

doesn't the visibility: hidden rule hold open the space the image would take if it were visible?  Does it not work with height?  if it doesn't then adding min-height isn't going to fix anything because some of your images are going to be taller than 100px and when the page actually loads the content will need to reflow (am I missing something?)

**Comment by tubalmartin** [comment]
The CSS provided is completely optional although recommended. 

**`min-height` may only be used when you defer the load of images below the fold**. That way, images get some height until loaded and the "jump" produced when an image gets loaded will be smaller.

Needless to say, in case `belowfold` defer mode is used, `min-height` should be set according to the height of your images.

I'll explain that in the docs.
