### ISSUE TITLE
allow fallback to have no breakpoint-name?

### ISSUE THREAD

**Issue by sswany** [tubalmartin/riloadr#8]
Is there any plan to support a filename without a `{breakpoint-name}` in the url at all? Or set a `{breakpoint-name}` of `name: ''`.  I ask because of legacy content that I'd rather not have to rename but add additional versions along with it and the content itself.

Thanks!

**Comment by tubalmartin** [comment]
You can set `''` (empty string) as a breakpoint name, no problemo.
