### ISSUE TITLE
Different image formats per breakpoint?

### ISSUE THREAD

**Issue by oli** [tubalmartin/riloadr#9]
I’ve noticed that sometimes e.g. a PNG will compress best for a small breakpoint, whereas a heavily compressed JPG is better for a HiDPI breakpoint. It would be nice if different image formats per breakpoint could be accommodated. It could be set via `data-*` per image, maybe something like:

``` html
<img class="responsive" data-src="iphone_slide_01.png" data-@2x="jpg" /><noscript>…
```

(where @2x is a breakpoint name, and other breakpoints use `data-src`’s extension). Another way would be to add to the Riloadr declaration using groups for each combination, maybe something like:

``` js
var group1 = new Riloadr({
    name: group1,
    breakpoints: [
        {name: '@1x', minWidth: 1}, // use extension in data-src
        {name: '2x', minWidth: 640, minDevicePixelRatio: 1.5, format: jpg} // change data-src to .jpg
    ]
});
var group2 = new Riloadr({
    name: group2,
    breakpoints: [
        {name: '@1x', minWidth: 1}, // use extension in data-src
        {name: '2x', minWidth: 640, minDevicePixelRatio: 1.5} // use extension in data-src
    ]
});
…
```

plus

``` html
<!-- this would use iphone_slide_01.png @1x, and iphone_slide_01.jpg @2x -->
<img class="responsive group1" data-src="iphone_slide_01.png" /><noscript>…
```

**Comment by tubalmartin** [comment]
I'll think about it.

**Comment by tubalmartin** [comment]
In my local copy of Riloadr 1.4.0 I've already implemented your suggestion :)

You can specify an image format for any breakpoint. If an `imgFormat` is set, then that format is used regardless of the image format used in `data-src`.

The way it works is as follows:

``` js
var group1 = new Riloadr({
    name: group1,
    breakpoints: [
        {name: 'mobile', minWidth: 1, imgFormat: 'png'}, // specify a format
        {name: 'desktop', minWidth: 640, imgFormat: 'jpg'} // specify a different format
    ]
});
```

``` html
<!-- Mobile first approach -->
<img class="group1" data-src="iphone_slide_01.png">
```

In this example, if the viewport is wider than 640px, the image that will be loaded will be `iphone_slide_01.jpg`. 

I'll release 1.4.0 in a few days, stay tuned!

**Comment by tubalmartin** [comment]
Version 1.4.0 is out and includes this feature, check it out and spread the word ;)
